server:
  servlet:
    session:
      timeout: 3600
spring:
  redis:
    host: 127.0.0.1
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/api-seed?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

api:
  exclude-urls: /api/v1/login,/api/v1/signin,/hello